# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import memory_pb2 as kagent_dot_api_dot_v1alpha1_dot_memory__pb2


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSession = channel.unary_unary(
                '/kagent.api.v1alpha1.MemoryService/AddSession',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionResponse.FromString,
                _registered_method=True)
        self.AddSessionBatch = channel.unary_unary(
                '/kagent.api.v1alpha1.MemoryService/AddSessionBatch',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionBatchRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionBatchResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/kagent.api.v1alpha1.MemoryService/Search',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceSearchRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceSearchResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/kagent.api.v1alpha1.MemoryService/List',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceListRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceListResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kagent.api.v1alpha1.MemoryService/Delete',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceDeleteRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceDeleteResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AddSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSessionBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSession,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionResponse.SerializeToString,
            ),
            'AddSessionBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSessionBatch,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionBatchRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionBatchResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceSearchRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceSearchResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceListRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceListResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceDeleteRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.MemoryService/AddSession',
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSessionBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.MemoryService/AddSessionBatch',
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionBatchRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceAddSessionBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.MemoryService/Search',
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceSearchRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.MemoryService/List',
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceListRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.MemoryService/Delete',
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceDeleteRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_memory__pb2.MemoryServiceDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
