# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import sessions_pb2 as kagent_dot_api_dot_v1alpha1_dot_sessions__pb2


class SessionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/ListSessions',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.ListSessionsByAgent = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/ListSessionsByAgent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsByAgentRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsByAgentResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/CreateSession',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/GetSession',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/UpdateSession',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpdateSessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/DeleteSession',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.AddSessionEvent = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/AddSessionEvent',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.AddSessionEventRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.AddSessionEventResponse.FromString,
                _registered_method=True)
        self.CreateSessionShare = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/CreateSessionShare',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionShareRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionShareResponse.FromString,
                _registered_method=True)
        self.ListSessionShares = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/ListSessionShares',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionSharesRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionSharesResponse.FromString,
                _registered_method=True)
        self.DeleteSessionShare = channel.unary_unary(
                '/kagent.api.v1alpha1.SessionService/DeleteSessionShare',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionShareRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionShareResponse.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessionsByAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSessionEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSessionShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessionShares(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSessionShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsResponse.SerializeToString,
            ),
            'ListSessionsByAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessionsByAgent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsByAgentRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsByAgentResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetSessionRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetSessionResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpdateSessionRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpdateSessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'AddSessionEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSessionEvent,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.AddSessionEventRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.AddSessionEventResponse.SerializeToString,
            ),
            'CreateSessionShare': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSessionShare,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionShareRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionShareResponse.SerializeToString,
            ),
            'ListSessionShares': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessionShares,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionSharesRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionSharesResponse.SerializeToString,
            ),
            'DeleteSessionShare': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSessionShare,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionShareRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionShareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/ListSessions',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessionsByAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/ListSessionsByAgent',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsByAgentRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionsByAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/CreateSession',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/GetSession',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetSessionRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/UpdateSession',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpdateSessionRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpdateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/DeleteSession',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSessionEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/AddSessionEvent',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.AddSessionEventRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.AddSessionEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSessionShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/CreateSessionShare',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionShareRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.CreateSessionShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessionShares(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/ListSessionShares',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionSharesRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListSessionSharesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSessionShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.SessionService/DeleteSessionShare',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionShareRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteSessionShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TaskStoreServiceStub:
    """TaskStoreService is the private persistence API used by agent runtimes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/UpsertTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpsertTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpsertTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/GetTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/DeleteTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/ListTasks',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListTasksResponse.FromString,
                _registered_method=True)


class TaskStoreServiceServicer:
    """TaskStoreService is the private persistence API used by agent runtimes.
    """

    def UpsertTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpsertTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpsertTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetTaskResponse.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListTasksRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.TaskStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.TaskStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskStoreService:
    """TaskStoreService is the private persistence API used by agent runtimes.
    """

    @staticmethod
    def UpsertTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/UpsertTask',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpsertTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.UpsertTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/GetTask',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/DeleteTask',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.DeleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/ListTasks',
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListTasksRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_sessions__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
