# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kagent.api.v1alpha1 import task_store_pb2 as kagent_dot_api_dot_v1alpha1_dot_task__store__pb2


class TaskStoreServiceStub:
    """TaskStoreService is the private persistence API for agent runtimes. Every call
    requires workload authority for the requested session. Public user and share
    credentials do not grant access to this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/CreateTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceCreateTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceCreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/GetTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceGetTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceGetTaskResponse.FromString,
                _registered_method=True)
        self.UpdateTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/UpdateTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceUpdateTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceUpdateTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/ListTasks',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceListTasksRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceListTasksResponse.FromString,
                _registered_method=True)
        self.SettleTask = channel.unary_unary(
                '/kagent.api.v1alpha1.TaskStoreService/SettleTask',
                request_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceSettleTaskRequest.SerializeToString,
                response_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceSettleTaskResponse.FromString,
                _registered_method=True)


class TaskStoreServiceServicer:
    """TaskStoreService is the private persistence API for agent runtimes. Every call
    requires workload authority for the requested session. Public user and share
    credentials do not grant access to this service.
    """

    def CreateTask(self, request, context):
        """CreateTask persists a new SDK task. Retrying the same task and payload
        returns its original version; a different creation with that ID conflicts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettleTask(self, request, context):
        """SettleTask acknowledges that native execution and SDK cleanup have stopped
        at this saved version and publishes its task state and history atomically.
        Runtime pause/suspend and checkpoint snapshot readiness are independent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceCreateTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceCreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceGetTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceGetTaskResponse.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceUpdateTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceUpdateTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceListTasksRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceListTasksResponse.SerializeToString,
            ),
            'SettleTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SettleTask,
                    request_deserializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceSettleTaskRequest.FromString,
                    response_serializer=kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceSettleTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kagent.api.v1alpha1.TaskStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kagent.api.v1alpha1.TaskStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskStoreService:
    """TaskStoreService is the private persistence API for agent runtimes. Every call
    requires workload authority for the requested session. Public user and share
    credentials do not grant access to this service.
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/CreateTask',
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceCreateTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceCreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/GetTask',
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceGetTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceGetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/UpdateTask',
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceUpdateTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceUpdateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/ListTasks',
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceListTasksRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SettleTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kagent.api.v1alpha1.TaskStoreService/SettleTask',
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceSettleTaskRequest.SerializeToString,
            kagent_dot_api_dot_v1alpha1_dot_task__store__pb2.TaskStoreServiceSettleTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
