syntax = "proto3";

package kagent.api.v1alpha1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/kagent-dev/kagent/go/api/gen/kagent/api/v1alpha1;apiv1alpha1";

service FeedbackService {
  rpc CreateFeedback(CreateFeedbackRequest) returns (CreateFeedbackResponse);
  rpc ListFeedback(ListFeedbackRequest) returns (ListFeedbackResponse);
}

message Feedback {
  int64 id = 1;
  google.protobuf.Timestamp created_at = 2;
  google.protobuf.Timestamp updated_at = 3;
  google.protobuf.Timestamp deleted_at = 4;
  string user_id = 5;
  optional int64 message_id = 6;
  bool is_positive = 7;
  string feedback_text = 8;
  optional string issue_type = 9;
}

message CreateFeedbackRequest {
  optional int64 message_id = 1;
  bool is_positive = 2;
  string feedback_text = 3;
  optional string issue_type = 4;
}

message CreateFeedbackResponse {}

message ListFeedbackRequest {}

message ListFeedbackResponse {
  repeated Feedback feedback = 1;
}
