//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha3

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A2AConfig) DeepCopyInto(out *A2AConfig) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]AgentSkill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2AConfig.
func (in *A2AConfig) DeepCopy() *A2AConfig {
	if in == nil {
		return nil
	}
	out := new(A2AConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarness) DeepCopyInto(out *AgentHarness) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarness.
func (in *AgentHarness) DeepCopy() *AgentHarness {
	if in == nil {
		return nil
	}
	out := new(AgentHarness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentHarness) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessChannel) DeepCopyInto(out *AgentHarnessChannel) {
	*out = *in
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(AgentHarnessTelegramChannelSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(AgentHarnessSlackChannelSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessChannel.
func (in *AgentHarnessChannel) DeepCopy() *AgentHarnessChannel {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessChannelCredential) DeepCopyInto(out *AgentHarnessChannelCredential) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessChannelCredential.
func (in *AgentHarnessChannelCredential) DeepCopy() *AgentHarnessChannelCredential {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessChannelCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessConnection) DeepCopyInto(out *AgentHarnessConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessConnection.
func (in *AgentHarnessConnection) DeepCopy() *AgentHarnessConnection {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessHermesSlackOptions) DeepCopyInto(out *AgentHarnessHermesSlackOptions) {
	*out = *in
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserIDsFrom != nil {
		in, out := &in.AllowedUserIDsFrom, &out.AllowedUserIDsFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessHermesSlackOptions.
func (in *AgentHarnessHermesSlackOptions) DeepCopy() *AgentHarnessHermesSlackOptions {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessHermesSlackOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessList) DeepCopyInto(out *AgentHarnessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentHarness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessList.
func (in *AgentHarnessList) DeepCopy() *AgentHarnessList {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentHarnessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessOpenClawSlackOptions) DeepCopyInto(out *AgentHarnessOpenClawSlackOptions) {
	*out = *in
	if in.AllowlistChannels != nil {
		in, out := &in.AllowlistChannels, &out.AllowlistChannels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InteractiveReplies != nil {
		in, out := &in.InteractiveReplies, &out.InteractiveReplies
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessOpenClawSlackOptions.
func (in *AgentHarnessOpenClawSlackOptions) DeepCopy() *AgentHarnessOpenClawSlackOptions {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessOpenClawSlackOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessSlackChannelSpec) DeepCopyInto(out *AgentHarnessSlackChannelSpec) {
	*out = *in
	in.BotToken.DeepCopyInto(&out.BotToken)
	in.AppToken.DeepCopyInto(&out.AppToken)
	if in.OpenClaw != nil {
		in, out := &in.OpenClaw, &out.OpenClaw
		*out = new(AgentHarnessOpenClawSlackOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Hermes != nil {
		in, out := &in.Hermes, &out.Hermes
		*out = new(AgentHarnessHermesSlackOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessSlackChannelSpec.
func (in *AgentHarnessSlackChannelSpec) DeepCopy() *AgentHarnessSlackChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessSlackChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessSpec) DeepCopyInto(out *AgentHarnessSpec) {
	*out = *in
	if in.Substrate != nil {
		in, out := &in.Substrate, &out.Substrate
		*out = new(AgentHarnessSubstrateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]AgentHarnessChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessSpec.
func (in *AgentHarnessSpec) DeepCopy() *AgentHarnessSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessStatus) DeepCopyInto(out *AgentHarnessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackendRef != nil {
		in, out := &in.BackendRef, &out.BackendRef
		*out = new(AgentHarnessStatusRef)
		**out = **in
	}
	if in.Connection != nil {
		in, out := &in.Connection, &out.Connection
		*out = new(AgentHarnessConnection)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessStatus.
func (in *AgentHarnessStatus) DeepCopy() *AgentHarnessStatus {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessStatusRef) DeepCopyInto(out *AgentHarnessStatusRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessStatusRef.
func (in *AgentHarnessStatusRef) DeepCopy() *AgentHarnessStatusRef {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessStatusRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessSubstrateSnapshotsConfig) DeepCopyInto(out *AgentHarnessSubstrateSnapshotsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessSubstrateSnapshotsConfig.
func (in *AgentHarnessSubstrateSnapshotsConfig) DeepCopy() *AgentHarnessSubstrateSnapshotsConfig {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessSubstrateSnapshotsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessSubstrateSpec) DeepCopyInto(out *AgentHarnessSubstrateSpec) {
	*out = *in
	if in.WorkerPoolRef != nil {
		in, out := &in.WorkerPoolRef, &out.WorkerPoolRef
		*out = new(TypedLocalReference)
		**out = **in
	}
	if in.SnapshotsConfig != nil {
		in, out := &in.SnapshotsConfig, &out.SnapshotsConfig
		*out = new(AgentHarnessSubstrateSnapshotsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessSubstrateSpec.
func (in *AgentHarnessSubstrateSpec) DeepCopy() *AgentHarnessSubstrateSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessSubstrateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessTelegramChannelSpec) DeepCopyInto(out *AgentHarnessTelegramChannelSpec) {
	*out = *in
	in.BotToken.DeepCopyInto(&out.BotToken)
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserIDsFrom != nil {
		in, out := &in.AllowedUserIDsFrom, &out.AllowedUserIDsFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessTelegramChannelSpec.
func (in *AgentHarnessTelegramChannelSpec) DeepCopy() *AgentHarnessTelegramChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessTelegramChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProvider) DeepCopyInto(out *AgentProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProvider.
func (in *AgentProvider) DeepCopy() *AgentProvider {
	if in == nil {
		return nil
	}
	out := new(AgentProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkill) DeepCopyInto(out *AgentSkill) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Examples != nil {
		in, out := &in.Examples, &out.Examples
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputModes != nil {
		in, out := &in.InputModes, &out.InputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutputModes != nil {
		in, out := &in.OutputModes, &out.OutputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkill.
func (in *AgentSkill) DeepCopy() *AgentSkill {
	if in == nil {
		return nil
	}
	out := new(AgentSkill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.BYO != nil {
		in, out := &in.BYO, &out.BYO
		*out = new(BYOAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Declarative != nil {
		in, out := &in.Declarative, &out.Declarative
		*out = new(DeclarativeAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(AgentProvider)
		**out = **in
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = new(SkillForAgent)
		(*in).DeepCopyInto(*out)
	}
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(SandboxConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Substrate != nil {
		in, out := &in.Substrate, &out.Substrate
		*out = new(SandboxSubstrateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(AllowedNamespaces)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplate) DeepCopyInto(out *AgentTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplate.
func (in *AgentTemplate) DeepCopy() *AgentTemplate {
	if in == nil {
		return nil
	}
	out := new(AgentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateConfigMapKeyReference) DeepCopyInto(out *AgentTemplateConfigMapKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateConfigMapKeyReference.
func (in *AgentTemplateConfigMapKeyReference) DeepCopy() *AgentTemplateConfigMapKeyReference {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateConfigMapKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateHarnessStatus) DeepCopyInto(out *AgentTemplateHarnessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateHarnessStatus.
func (in *AgentTemplateHarnessStatus) DeepCopy() *AgentTemplateHarnessStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateHarnessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateList) DeepCopyInto(out *AgentTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateList.
func (in *AgentTemplateList) DeepCopy() *AgentTemplateList {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateLocalReference) DeepCopyInto(out *AgentTemplateLocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateLocalReference.
func (in *AgentTemplateLocalReference) DeepCopy() *AgentTemplateLocalReference {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateLocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplatePromptSource) DeepCopyInto(out *AgentTemplatePromptSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplatePromptSource.
func (in *AgentTemplatePromptSource) DeepCopy() *AgentTemplatePromptSource {
	if in == nil {
		return nil
	}
	out := new(AgentTemplatePromptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplatePromptTemplateSpec) DeepCopyInto(out *AgentTemplatePromptTemplateSpec) {
	*out = *in
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]AgentTemplatePromptSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplatePromptTemplateSpec.
func (in *AgentTemplatePromptTemplateSpec) DeepCopy() *AgentTemplatePromptTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTemplatePromptTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateSkill) DeepCopyInto(out *AgentTemplateSkill) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateSkill.
func (in *AgentTemplateSkill) DeepCopy() *AgentTemplateSkill {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateSkill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateSpec) DeepCopyInto(out *AgentTemplateSpec) {
	*out = *in
	out.ModelConfig = in.ModelConfig
	if in.SystemPromptFrom != nil {
		in, out := &in.SystemPromptFrom, &out.SystemPromptFrom
		*out = new(AgentTemplateConfigMapKeyReference)
		**out = **in
	}
	if in.PromptTemplate != nil {
		in, out := &in.PromptTemplate, &out.PromptTemplate
		*out = new(AgentTemplatePromptTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]AgentTemplateSkill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PluginBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateSpec.
func (in *AgentTemplateSpec) DeepCopy() *AgentTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateStatus) DeepCopyInto(out *AgentTemplateStatus) {
	*out = *in
	if in.Harnesses != nil {
		in, out := &in.Harnesses, &out.Harnesses
		*out = make([]AgentTemplateHarnessStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateStatus.
func (in *AgentTemplateStatus) DeepCopy() *AgentTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTemplateTypedLocalReference) DeepCopyInto(out *AgentTemplateTypedLocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTemplateTypedLocalReference.
func (in *AgentTemplateTypedLocalReference) DeepCopy() *AgentTemplateTypedLocalReference {
	if in == nil {
		return nil
	}
	out := new(AgentTemplateTypedLocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentToolBinding) DeepCopyInto(out *AgentToolBinding) {
	*out = *in
	out.TemplateRef = in.TemplateRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentToolBinding.
func (in *AgentToolBinding) DeepCopy() *AgentToolBinding {
	if in == nil {
		return nil
	}
	out := new(AgentToolBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedNamespaces) DeepCopyInto(out *AllowedNamespaces) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedNamespaces.
func (in *AllowedNamespaces) DeepCopy() *AllowedNamespaces {
	if in == nil {
		return nil
	}
	out := new(AllowedNamespaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicConfig) DeepCopyInto(out *AnthropicConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicConfig.
func (in *AnthropicConfig) DeepCopy() *AnthropicConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicVertexAIConfig) DeepCopyInto(out *AnthropicVertexAIConfig) {
	*out = *in
	in.BaseVertexAIConfig.DeepCopyInto(&out.BaseVertexAIConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicVertexAIConfig.
func (in *AnthropicVertexAIConfig) DeepCopy() *AnthropicVertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicVertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSource) DeepCopyInto(out *ArtifactSource) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitArtifact)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(BucketArtifact)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSource.
func (in *ArtifactSource) DeepCopy() *ArtifactSource {
	if in == nil {
		return nil
	}
	out := new(ArtifactSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureOpenAIConfig) DeepCopyInto(out *AzureOpenAIConfig) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureOpenAIConfig.
func (in *AzureOpenAIConfig) DeepCopy() *AzureOpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(AzureOpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BYOAgentSpec) DeepCopyInto(out *BYOAgentSpec) {
	*out = *in
	if in.Cmd != nil {
		in, out := &in.Cmd, &out.Cmd
		*out = new(string)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BYOAgentSpec.
func (in *BYOAgentSpec) DeepCopy() *BYOAgentSpec {
	if in == nil {
		return nil
	}
	out := new(BYOAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseVertexAIConfig) DeepCopyInto(out *BaseVertexAIConfig) {
	*out = *in
	if in.StopSequences != nil {
		in, out := &in.StopSequences, &out.StopSequences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseVertexAIConfig.
func (in *BaseVertexAIConfig) DeepCopy() *BaseVertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(BaseVertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockConfig) DeepCopyInto(out *BedrockConfig) {
	*out = *in
	if in.AdditionalModelRequestFields != nil {
		in, out := &in.AdditionalModelRequestFields, &out.AdditionalModelRequestFields
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Guardrail != nil {
		in, out := &in.Guardrail, &out.Guardrail
		*out = new(BedrockGuardrailConfig)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockConfig.
func (in *BedrockConfig) DeepCopy() *BedrockConfig {
	if in == nil {
		return nil
	}
	out := new(BedrockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockGuardrailConfig) DeepCopyInto(out *BedrockGuardrailConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockGuardrailConfig.
func (in *BedrockGuardrailConfig) DeepCopy() *BedrockGuardrailConfig {
	if in == nil {
		return nil
	}
	out := new(BedrockGuardrailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketArtifact) DeepCopyInto(out *BucketArtifact) {
	*out = *in
	out.S3 = in.S3
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketArtifact.
func (in *BucketArtifact) DeepCopy() *BucketArtifact {
	if in == nil {
		return nil
	}
	out := new(BucketArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaudeHarness) DeepCopyInto(out *ClaudeHarness) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaudeHarness.
func (in *ClaudeHarness) DeepCopy() *ClaudeHarness {
	if in == nil {
		return nil
	}
	out := new(ClaudeHarness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodexHarness) DeepCopyInto(out *CodexHarness) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodexHarness.
func (in *CodexHarness) DeepCopy() *CodexHarness {
	if in == nil {
		return nil
	}
	out := new(CodexHarness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextCompressionConfig) DeepCopyInto(out *ContextCompressionConfig) {
	*out = *in
	if in.CompactionInterval != nil {
		in, out := &in.CompactionInterval, &out.CompactionInterval
		*out = new(int)
		**out = **in
	}
	if in.OverlapSize != nil {
		in, out := &in.OverlapSize, &out.OverlapSize
		*out = new(int)
		**out = **in
	}
	if in.Summarizer != nil {
		in, out := &in.Summarizer, &out.Summarizer
		*out = new(ContextSummarizerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenThreshold != nil {
		in, out := &in.TokenThreshold, &out.TokenThreshold
		*out = new(int)
		**out = **in
	}
	if in.EventRetentionSize != nil {
		in, out := &in.EventRetentionSize, &out.EventRetentionSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextCompressionConfig.
func (in *ContextCompressionConfig) DeepCopy() *ContextCompressionConfig {
	if in == nil {
		return nil
	}
	out := new(ContextCompressionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextConfig) DeepCopyInto(out *ContextConfig) {
	*out = *in
	if in.Compaction != nil {
		in, out := &in.Compaction, &out.Compaction
		*out = new(ContextCompressionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextConfig.
func (in *ContextConfig) DeepCopy() *ContextConfig {
	if in == nil {
		return nil
	}
	out := new(ContextConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextSummarizerConfig) DeepCopyInto(out *ContextSummarizerConfig) {
	*out = *in
	if in.ModelConfig != nil {
		in, out := &in.ModelConfig, &out.ModelConfig
		*out = new(string)
		**out = **in
	}
	if in.PromptTemplate != nil {
		in, out := &in.PromptTemplate, &out.PromptTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextSummarizerConfig.
func (in *ContextSummarizerConfig) DeepCopy() *ContextSummarizerConfig {
	if in == nil {
		return nil
	}
	out := new(ContextSummarizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeclarativeAgentSpec) DeepCopyInto(out *DeclarativeAgentSpec) {
	*out = *in
	if in.SystemMessageFrom != nil {
		in, out := &in.SystemMessageFrom, &out.SystemMessageFrom
		*out = new(ValueSource)
		**out = **in
	}
	if in.PromptTemplate != nil {
		in, out := &in.PromptTemplate, &out.PromptTemplate
		*out = new(PromptTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]*Tool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tool)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.A2AConfig != nil {
		in, out := &in.A2AConfig, &out.A2AConfig
		*out = new(A2AConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemorySpec)
		**out = **in
	}
	if in.ShareTools != nil {
		in, out := &in.ShareTools, &out.ShareTools
		*out = new(bool)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(ContextConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeclarativeAgentSpec.
func (in *DeclarativeAgentSpec) DeepCopy() *DeclarativeAgentSpec {
	if in == nil {
		return nil
	}
	out := new(DeclarativeAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryConfig) DeepCopyInto(out *FoundryConfig) {
	*out = *in
	if in.EndpointFrom != nil {
		in, out := &in.EndpointFrom, &out.EndpointFrom
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryConfig.
func (in *FoundryConfig) DeepCopy() *FoundryConfig {
	if in == nil {
		return nil
	}
	out := new(FoundryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GDCHServiceAccountConfig) DeepCopyInto(out *GDCHServiceAccountConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GDCHServiceAccountConfig.
func (in *GDCHServiceAccountConfig) DeepCopy() *GDCHServiceAccountConfig {
	if in == nil {
		return nil
	}
	out := new(GDCHServiceAccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiConfig) DeepCopyInto(out *GeminiConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiConfig.
func (in *GeminiConfig) DeepCopy() *GeminiConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiVertexAIConfig) DeepCopyInto(out *GeminiVertexAIConfig) {
	*out = *in
	in.BaseVertexAIConfig.DeepCopyInto(&out.BaseVertexAIConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiVertexAIConfig.
func (in *GeminiVertexAIConfig) DeepCopy() *GeminiVertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiVertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitArtifact) DeepCopyInto(out *GitArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitArtifact.
func (in *GitArtifact) DeepCopy() *GitArtifact {
	if in == nil {
		return nil
	}
	out := new(GitArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepo) DeepCopyInto(out *GitRepo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepo.
func (in *GitRepo) DeepCopy() *GitRepo {
	if in == nil {
		return nil
	}
	out := new(GitRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Harness) DeepCopyInto(out *Harness) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Harness.
func (in *Harness) DeepCopy() *Harness {
	if in == nil {
		return nil
	}
	out := new(Harness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Harness) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessAgentTemplateAdmission) DeepCopyInto(out *HarnessAgentTemplateAdmission) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessAgentTemplateAdmission.
func (in *HarnessAgentTemplateAdmission) DeepCopy() *HarnessAgentTemplateAdmission {
	if in == nil {
		return nil
	}
	out := new(HarnessAgentTemplateAdmission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessCapabilities) DeepCopyInto(out *HarnessCapabilities) {
	*out = *in
	if in.InputModalities != nil {
		in, out := &in.InputModalities, &out.InputModalities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutputModalities != nil {
		in, out := &in.OutputModalities, &out.OutputModalities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessCapabilities.
func (in *HarnessCapabilities) DeepCopy() *HarnessCapabilities {
	if in == nil {
		return nil
	}
	out := new(HarnessCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessEnvVar) DeepCopyInto(out *HarnessEnvVar) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.CredentialRef != nil {
		in, out := &in.CredentialRef, &out.CredentialRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessEnvVar.
func (in *HarnessEnvVar) DeepCopy() *HarnessEnvVar {
	if in == nil {
		return nil
	}
	out := new(HarnessEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessList) DeepCopyInto(out *HarnessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Harness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessList.
func (in *HarnessList) DeepCopy() *HarnessList {
	if in == nil {
		return nil
	}
	out := new(HarnessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessSnapshotPolicy) DeepCopyInto(out *HarnessSnapshotPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessSnapshotPolicy.
func (in *HarnessSnapshotPolicy) DeepCopy() *HarnessSnapshotPolicy {
	if in == nil {
		return nil
	}
	out := new(HarnessSnapshotPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessSpec) DeepCopyInto(out *HarnessSpec) {
	*out = *in
	if in.Kagent != nil {
		in, out := &in.Kagent, &out.Kagent
		*out = new(KagentHarness)
		**out = **in
	}
	if in.Codex != nil {
		in, out := &in.Codex, &out.Codex
		*out = new(CodexHarness)
		**out = **in
	}
	if in.Claude != nil {
		in, out := &in.Claude, &out.Claude
		*out = new(ClaudeHarness)
		**out = **in
	}
	out.Workload = in.Workload
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]HarnessEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Substrate = in.Substrate
	if in.AllowedAgentTemplates != nil {
		in, out := &in.AllowedAgentTemplates, &out.AllowedAgentTemplates
		*out = new(HarnessAgentTemplateAdmission)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessSpec.
func (in *HarnessSpec) DeepCopy() *HarnessSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessStatus) DeepCopyInto(out *HarnessStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(HarnessCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessStatus.
func (in *HarnessStatus) DeepCopy() *HarnessStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessSubstratePolicy) DeepCopyInto(out *HarnessSubstratePolicy) {
	*out = *in
	out.WorkerPoolRef = in.WorkerPoolRef
	out.SnapshotPolicy = in.SnapshotPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessSubstratePolicy.
func (in *HarnessSubstratePolicy) DeepCopy() *HarnessSubstratePolicy {
	if in == nil {
		return nil
	}
	out := new(HarnessSubstratePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessWorkload) DeepCopyInto(out *HarnessWorkload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessWorkload.
func (in *HarnessWorkload) DeepCopy() *HarnessWorkload {
	if in == nil {
		return nil
	}
	out := new(HarnessWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KagentHarness) DeepCopyInto(out *KagentHarness) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KagentHarness.
func (in *KagentHarness) DeepCopy() *KagentHarness {
	if in == nil {
		return nil
	}
	out := new(KagentHarness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPTool) DeepCopyInto(out *MCPTool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPTool.
func (in *MCPTool) DeepCopy() *MCPTool {
	if in == nil {
		return nil
	}
	out := new(MCPTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPToolBinding) DeepCopyInto(out *MCPToolBinding) {
	*out = *in
	out.Server = in.Server
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPToolBinding.
func (in *MCPToolBinding) DeepCopy() *MCPToolBinding {
	if in == nil {
		return nil
	}
	out := new(MCPToolBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpServerTool) DeepCopyInto(out *McpServerTool) {
	*out = *in
	out.TypedReference = in.TypedReference
	if in.ToolNames != nil {
		in, out := &in.ToolNames, &out.ToolNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireApproval != nil {
		in, out := &in.RequireApproval, &out.RequireApproval
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpServerTool.
func (in *McpServerTool) DeepCopy() *McpServerTool {
	if in == nil {
		return nil
	}
	out := new(McpServerTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySpec.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigList) DeepCopyInto(out *ModelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigList.
func (in *ModelConfigList) DeepCopy() *ModelConfigList {
	if in == nil {
		return nil
	}
	out := new(ModelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigSpec) DeepCopyInto(out *ModelConfigSpec) {
	*out = *in
	if in.DefaultHeaders != nil {
		in, out := &in.DefaultHeaders, &out.DefaultHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicConfig)
		**out = **in
	}
	if in.AzureOpenAI != nil {
		in, out := &in.AzureOpenAI, &out.AzureOpenAI
		*out = new(AzureOpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ollama != nil {
		in, out := &in.Ollama, &out.Ollama
		*out = new(OllamaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gemini != nil {
		in, out := &in.Gemini, &out.Gemini
		*out = new(GeminiConfig)
		**out = **in
	}
	if in.GeminiVertexAI != nil {
		in, out := &in.GeminiVertexAI, &out.GeminiVertexAI
		*out = new(GeminiVertexAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AnthropicVertexAI != nil {
		in, out := &in.AnthropicVertexAI, &out.AnthropicVertexAI
		*out = new(AnthropicVertexAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SAPAICore != nil {
		in, out := &in.SAPAICore, &out.SAPAICore
		*out = new(SAPAICoreConfig)
		**out = **in
	}
	if in.Foundry != nil {
		in, out := &in.Foundry, &out.Foundry
		*out = new(FoundryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigSpec.
func (in *ModelConfigSpec) DeepCopy() *ModelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ModelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigStatus) DeepCopyInto(out *ModelConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigStatus.
func (in *ModelConfigStatus) DeepCopy() *ModelConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ModelConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfig) DeepCopyInto(out *ModelProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfig.
func (in *ModelProviderConfig) DeepCopy() *ModelProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfigList) DeepCopyInto(out *ModelProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfigList.
func (in *ModelProviderConfigList) DeepCopy() *ModelProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfigSpec) DeepCopyInto(out *ModelProviderConfigSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfigSpec.
func (in *ModelProviderConfigSpec) DeepCopy() *ModelProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfigStatus) DeepCopyInto(out *ModelProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredModels != nil {
		in, out := &in.DiscoveredModels, &out.DiscoveredModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastDiscoveryTime != nil {
		in, out := &in.LastDiscoveryTime, &out.LastDiscoveryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfigStatus.
func (in *ModelProviderConfigStatus) DeepCopy() *ModelProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OllamaConfig) DeepCopyInto(out *OllamaConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OllamaConfig.
func (in *OllamaConfig) DeepCopy() *OllamaConfig {
	if in == nil {
		return nil
	}
	out := new(OllamaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIConfig) DeepCopyInto(out *OpenAIConfig) {
	*out = *in
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(int)
		**out = **in
	}
	if in.N != nil {
		in, out := &in.N, &out.N
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.ReasoningEffort != nil {
		in, out := &in.ReasoningEffort, &out.ReasoningEffort
		*out = new(OpenAIReasoningEffort)
		**out = **in
	}
	if in.APIFormat != nil {
		in, out := &in.APIFormat, &out.APIFormat
		*out = new(OpenAIAPIFormat)
		**out = **in
	}
	if in.TokenExchange != nil {
		in, out := &in.TokenExchange, &out.TokenExchange
		*out = new(TokenExchangeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIConfig.
func (in *OpenAIConfig) DeepCopy() *OpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginBundle) DeepCopyInto(out *PluginBundle) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginBundle.
func (in *PluginBundle) DeepCopy() *PluginBundle {
	if in == nil {
		return nil
	}
	out := new(PluginBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptSource) DeepCopyInto(out *PromptSource) {
	*out = *in
	out.TypedLocalReference = in.TypedLocalReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptSource.
func (in *PromptSource) DeepCopy() *PromptSource {
	if in == nil {
		return nil
	}
	out := new(PromptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplateSpec) DeepCopyInto(out *PromptTemplateSpec) {
	*out = *in
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]PromptSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplateSpec.
func (in *PromptTemplateSpec) DeepCopy() *PromptTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServer) DeepCopyInto(out *RemoteMCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServer.
func (in *RemoteMCPServer) DeepCopy() *RemoteMCPServer {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteMCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServerList) DeepCopyInto(out *RemoteMCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteMCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServerList.
func (in *RemoteMCPServerList) DeepCopy() *RemoteMCPServerList {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteMCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServerSpec) DeepCopyInto(out *RemoteMCPServerSpec) {
	*out = *in
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]ValueRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SseReadTimeout != nil {
		in, out := &in.SseReadTimeout, &out.SseReadTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TerminateOnClose != nil {
		in, out := &in.TerminateOnClose, &out.TerminateOnClose
		*out = new(bool)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(AllowedNamespaces)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServerSpec.
func (in *RemoteMCPServerSpec) DeepCopy() *RemoteMCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServerStatus) DeepCopyInto(out *RemoteMCPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredTools != nil {
		in, out := &in.DiscoveredTools, &out.DiscoveredTools
		*out = make([]*MCPTool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MCPTool)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServerStatus.
func (in *RemoteMCPServerStatus) DeepCopy() *RemoteMCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Object) DeepCopyInto(out *S3Object) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Object.
func (in *S3Object) DeepCopy() *S3Object {
	if in == nil {
		return nil
	}
	out := new(S3Object)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SkillRef) DeepCopyInto(out *S3SkillRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SkillRef.
func (in *S3SkillRef) DeepCopy() *S3SkillRef {
	if in == nil {
		return nil
	}
	out := new(S3SkillRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAPAICoreConfig) DeepCopyInto(out *SAPAICoreConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAPAICoreConfig.
func (in *SAPAICoreConfig) DeepCopy() *SAPAICoreConfig {
	if in == nil {
		return nil
	}
	out := new(SAPAICoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAgent) DeepCopyInto(out *SandboxAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAgent.
func (in *SandboxAgent) DeepCopy() *SandboxAgent {
	if in == nil {
		return nil
	}
	out := new(SandboxAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAgentList) DeepCopyInto(out *SandboxAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAgentList.
func (in *SandboxAgentList) DeepCopy() *SandboxAgentList {
	if in == nil {
		return nil
	}
	out := new(SandboxAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxConfig) DeepCopyInto(out *SandboxConfig) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxConfig.
func (in *SandboxConfig) DeepCopy() *SandboxConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSubstrateSpec) DeepCopyInto(out *SandboxSubstrateSpec) {
	*out = *in
	if in.WorkerPoolRef != nil {
		in, out := &in.WorkerPoolRef, &out.WorkerPoolRef
		*out = new(TypedLocalReference)
		**out = **in
	}
	if in.SnapshotsConfig != nil {
		in, out := &in.SnapshotsConfig, &out.SnapshotsConfig
		*out = new(AgentHarnessSubstrateSnapshotsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSubstrateSpec.
func (in *SandboxSubstrateSpec) DeepCopy() *SandboxSubstrateSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSubstrateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillForAgent) DeepCopyInto(out *SkillForAgent) {
	*out = *in
	if in.Refs != nil {
		in, out := &in.Refs, &out.Refs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.GitAuthSecretRef != nil {
		in, out := &in.GitAuthSecretRef, &out.GitAuthSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.GitRefs != nil {
		in, out := &in.GitRefs, &out.GitRefs
		*out = make([]GitRepo, len(*in))
		copy(*out, *in)
	}
	if in.S3Refs != nil {
		in, out := &in.S3Refs, &out.S3Refs
		*out = make([]S3SkillRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillForAgent.
func (in *SkillForAgent) DeepCopy() *SkillForAgent {
	if in == nil {
		return nil
	}
	out := new(SkillForAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenExchangeConfig) DeepCopyInto(out *TokenExchangeConfig) {
	*out = *in
	if in.GDCHServiceAccount != nil {
		in, out := &in.GDCHServiceAccount, &out.GDCHServiceAccount
		*out = new(GDCHServiceAccountConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenExchangeConfig.
func (in *TokenExchangeConfig) DeepCopy() *TokenExchangeConfig {
	if in == nil {
		return nil
	}
	out := new(TokenExchangeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	if in.McpServer != nil {
		in, out := &in.McpServer, &out.McpServer
		*out = new(McpServerTool)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(TypedReference)
		**out = **in
	}
	if in.IsolateSessions != nil {
		in, out := &in.IsolateSessions, &out.IsolateSessions
		*out = new(bool)
		**out = **in
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]ValueRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBinding) DeepCopyInto(out *ToolBinding) {
	*out = *in
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPToolBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(AgentToolBinding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBinding.
func (in *ToolBinding) DeepCopy() *ToolBinding {
	if in == nil {
		return nil
	}
	out := new(ToolBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypedLocalReference) DeepCopyInto(out *TypedLocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedLocalReference.
func (in *TypedLocalReference) DeepCopy() *TypedLocalReference {
	if in == nil {
		return nil
	}
	out := new(TypedLocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypedReference) DeepCopyInto(out *TypedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedReference.
func (in *TypedReference) DeepCopy() *TypedReference {
	if in == nil {
		return nil
	}
	out := new(TypedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueRef) DeepCopyInto(out *ValueRef) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueRef.
func (in *ValueRef) DeepCopy() *ValueRef {
	if in == nil {
		return nil
	}
	out := new(ValueRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSource) DeepCopyInto(out *ValueSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSource.
func (in *ValueSource) DeepCopy() *ValueSource {
	if in == nil {
		return nil
	}
	out := new(ValueSource)
	in.DeepCopyInto(out)
	return out
}
