// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentTemplatesGetter has a method to return a AgentTemplateInterface.
// A group's client should implement this interface.
type AgentTemplatesGetter interface {
	AgentTemplates(namespace string) AgentTemplateInterface
}

// AgentTemplateInterface has methods to work with AgentTemplate resources.
type AgentTemplateInterface interface {
	Create(ctx context.Context, agentTemplate *apiv1alpha3.AgentTemplate, opts v1.CreateOptions) (*apiv1alpha3.AgentTemplate, error)
	Update(ctx context.Context, agentTemplate *apiv1alpha3.AgentTemplate, opts v1.UpdateOptions) (*apiv1alpha3.AgentTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentTemplate *apiv1alpha3.AgentTemplate, opts v1.UpdateOptions) (*apiv1alpha3.AgentTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.AgentTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.AgentTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.AgentTemplate, err error)
	AgentTemplateExpansion
}

// agentTemplates implements AgentTemplateInterface
type agentTemplates struct {
	*gentype.ClientWithList[*apiv1alpha3.AgentTemplate, *apiv1alpha3.AgentTemplateList]
}

// newAgentTemplates returns a AgentTemplates
func newAgentTemplates(c *ApiV1alpha3Client, namespace string) *agentTemplates {
	return &agentTemplates{
		gentype.NewClientWithList[*apiv1alpha3.AgentTemplate, *apiv1alpha3.AgentTemplateList](
			"agenttemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.AgentTemplate { return &apiv1alpha3.AgentTemplate{} },
			func() *apiv1alpha3.AgentTemplateList { return &apiv1alpha3.AgentTemplateList{} },
		),
	}
}
