// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentsGetter has a method to return a AgentInterface.
// A group's client should implement this interface.
type AgentsGetter interface {
	Agents(namespace string) AgentInterface
}

// AgentInterface has methods to work with Agent resources.
type AgentInterface interface {
	Create(ctx context.Context, agent *apiv1alpha3.Agent, opts v1.CreateOptions) (*apiv1alpha3.Agent, error)
	Update(ctx context.Context, agent *apiv1alpha3.Agent, opts v1.UpdateOptions) (*apiv1alpha3.Agent, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agent *apiv1alpha3.Agent, opts v1.UpdateOptions) (*apiv1alpha3.Agent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.Agent, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.AgentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.Agent, err error)
	AgentExpansion
}

// agents implements AgentInterface
type agents struct {
	*gentype.ClientWithList[*apiv1alpha3.Agent, *apiv1alpha3.AgentList]
}

// newAgents returns a Agents
func newAgents(c *ApiV1alpha3Client, namespace string) *agents {
	return &agents{
		gentype.NewClientWithList[*apiv1alpha3.Agent, *apiv1alpha3.AgentList](
			"agents",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.Agent { return &apiv1alpha3.Agent{} },
			func() *apiv1alpha3.AgentList { return &apiv1alpha3.AgentList{} },
		),
	}
}
