// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	http "net/http"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	rest "k8s.io/client-go/rest"
)

type ApiV1alpha3Interface interface {
	RESTClient() rest.Interface
	AgentTemplatesGetter
	HarnessesGetter
	ModelConfigsGetter
	RemoteMCPServersGetter
}

// ApiV1alpha3Client is used to interact with features provided by the api group.
type ApiV1alpha3Client struct {
	restClient rest.Interface
}

func (c *ApiV1alpha3Client) AgentTemplates(namespace string) AgentTemplateInterface {
	return newAgentTemplates(c, namespace)
}

func (c *ApiV1alpha3Client) Harnesses(namespace string) HarnessInterface {
	return newHarnesses(c, namespace)
}

func (c *ApiV1alpha3Client) ModelConfigs(namespace string) ModelConfigInterface {
	return newModelConfigs(c, namespace)
}

func (c *ApiV1alpha3Client) RemoteMCPServers(namespace string) RemoteMCPServerInterface {
	return newRemoteMCPServers(c, namespace)
}

// NewForConfig creates a new ApiV1alpha3Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ApiV1alpha3Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ApiV1alpha3Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ApiV1alpha3Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ApiV1alpha3Client{client}, nil
}

// NewForConfigOrDie creates a new ApiV1alpha3Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ApiV1alpha3Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ApiV1alpha3Client for the given RESTClient.
func New(c rest.Interface) *ApiV1alpha3Client {
	return &ApiV1alpha3Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apiv1alpha3.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ApiV1alpha3Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
