// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

type AgentTemplateExpansion interface{}

type HarnessExpansion interface{}

type ModelConfigExpansion interface{}

type RemoteMCPServerExpansion interface{}
