// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HarnessesGetter has a method to return a HarnessInterface.
// A group's client should implement this interface.
type HarnessesGetter interface {
	Harnesses(namespace string) HarnessInterface
}

// HarnessInterface has methods to work with Harness resources.
type HarnessInterface interface {
	Create(ctx context.Context, harness *apiv1alpha3.Harness, opts v1.CreateOptions) (*apiv1alpha3.Harness, error)
	Update(ctx context.Context, harness *apiv1alpha3.Harness, opts v1.UpdateOptions) (*apiv1alpha3.Harness, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, harness *apiv1alpha3.Harness, opts v1.UpdateOptions) (*apiv1alpha3.Harness, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.Harness, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.HarnessList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.Harness, err error)
	HarnessExpansion
}

// harnesses implements HarnessInterface
type harnesses struct {
	*gentype.ClientWithList[*apiv1alpha3.Harness, *apiv1alpha3.HarnessList]
}

// newHarnesses returns a Harnesses
func newHarnesses(c *ApiV1alpha3Client, namespace string) *harnesses {
	return &harnesses{
		gentype.NewClientWithList[*apiv1alpha3.Harness, *apiv1alpha3.HarnessList](
			"harnesses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.Harness { return &apiv1alpha3.Harness{} },
			func() *apiv1alpha3.HarnessList { return &apiv1alpha3.HarnessList{} },
		),
	}
}
