// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModelConfigsGetter has a method to return a ModelConfigInterface.
// A group's client should implement this interface.
type ModelConfigsGetter interface {
	ModelConfigs(namespace string) ModelConfigInterface
}

// ModelConfigInterface has methods to work with ModelConfig resources.
type ModelConfigInterface interface {
	Create(ctx context.Context, modelConfig *apiv1alpha3.ModelConfig, opts v1.CreateOptions) (*apiv1alpha3.ModelConfig, error)
	Update(ctx context.Context, modelConfig *apiv1alpha3.ModelConfig, opts v1.UpdateOptions) (*apiv1alpha3.ModelConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelConfig *apiv1alpha3.ModelConfig, opts v1.UpdateOptions) (*apiv1alpha3.ModelConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.ModelConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.ModelConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.ModelConfig, err error)
	ModelConfigExpansion
}

// modelConfigs implements ModelConfigInterface
type modelConfigs struct {
	*gentype.ClientWithList[*apiv1alpha3.ModelConfig, *apiv1alpha3.ModelConfigList]
}

// newModelConfigs returns a ModelConfigs
func newModelConfigs(c *ApiV1alpha3Client, namespace string) *modelConfigs {
	return &modelConfigs{
		gentype.NewClientWithList[*apiv1alpha3.ModelConfig, *apiv1alpha3.ModelConfigList](
			"modelconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.ModelConfig { return &apiv1alpha3.ModelConfig{} },
			func() *apiv1alpha3.ModelConfigList { return &apiv1alpha3.ModelConfigList{} },
		),
	}
}
