// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RemoteMCPServersGetter has a method to return a RemoteMCPServerInterface.
// A group's client should implement this interface.
type RemoteMCPServersGetter interface {
	RemoteMCPServers(namespace string) RemoteMCPServerInterface
}

// RemoteMCPServerInterface has methods to work with RemoteMCPServer resources.
type RemoteMCPServerInterface interface {
	Create(ctx context.Context, remoteMCPServer *apiv1alpha3.RemoteMCPServer, opts v1.CreateOptions) (*apiv1alpha3.RemoteMCPServer, error)
	Update(ctx context.Context, remoteMCPServer *apiv1alpha3.RemoteMCPServer, opts v1.UpdateOptions) (*apiv1alpha3.RemoteMCPServer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, remoteMCPServer *apiv1alpha3.RemoteMCPServer, opts v1.UpdateOptions) (*apiv1alpha3.RemoteMCPServer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.RemoteMCPServer, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.RemoteMCPServerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.RemoteMCPServer, err error)
	RemoteMCPServerExpansion
}

// remoteMCPServers implements RemoteMCPServerInterface
type remoteMCPServers struct {
	*gentype.ClientWithList[*apiv1alpha3.RemoteMCPServer, *apiv1alpha3.RemoteMCPServerList]
}

// newRemoteMCPServers returns a RemoteMCPServers
func newRemoteMCPServers(c *ApiV1alpha3Client, namespace string) *remoteMCPServers {
	return &remoteMCPServers{
		gentype.NewClientWithList[*apiv1alpha3.RemoteMCPServer, *apiv1alpha3.RemoteMCPServerList](
			"remotemcpservers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.RemoteMCPServer { return &apiv1alpha3.RemoteMCPServer{} },
			func() *apiv1alpha3.RemoteMCPServerList { return &apiv1alpha3.RemoteMCPServerList{} },
		),
	}
}
