// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SandboxTemplatesGetter has a method to return a SandboxTemplateInterface.
// A group's client should implement this interface.
type SandboxTemplatesGetter interface {
	SandboxTemplates(namespace string) SandboxTemplateInterface
}

// SandboxTemplateInterface has methods to work with SandboxTemplate resources.
type SandboxTemplateInterface interface {
	Create(ctx context.Context, sandboxTemplate *apiv1alpha3.SandboxTemplate, opts v1.CreateOptions) (*apiv1alpha3.SandboxTemplate, error)
	Update(ctx context.Context, sandboxTemplate *apiv1alpha3.SandboxTemplate, opts v1.UpdateOptions) (*apiv1alpha3.SandboxTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, sandboxTemplate *apiv1alpha3.SandboxTemplate, opts v1.UpdateOptions) (*apiv1alpha3.SandboxTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.SandboxTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.SandboxTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.SandboxTemplate, err error)
	SandboxTemplateExpansion
}

// sandboxTemplates implements SandboxTemplateInterface
type sandboxTemplates struct {
	*gentype.ClientWithList[*apiv1alpha3.SandboxTemplate, *apiv1alpha3.SandboxTemplateList]
}

// newSandboxTemplates returns a SandboxTemplates
func newSandboxTemplates(c *ApiV1alpha3Client, namespace string) *sandboxTemplates {
	return &sandboxTemplates{
		gentype.NewClientWithList[*apiv1alpha3.SandboxTemplate, *apiv1alpha3.SandboxTemplateList](
			"sandboxtemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.SandboxTemplate { return &apiv1alpha3.SandboxTemplate{} },
			func() *apiv1alpha3.SandboxTemplateList { return &apiv1alpha3.SandboxTemplateList{} },
		),
	}
}
