apiVersion: kagent.dev/v1alpha3
kind: SandboxAgent
metadata:
  name: basic-openai-agent
spec:
  description: A basic OpenAI agent with calculator and weather tools
  type: BYO
  byo:
    image: localhost:5001/basic-openai:latest
    cmd: python
    args: [samples/openai/basic_agent/basic_agent/agent.py]
    env:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: kagent-openai
            key: OPENAI_API_KEY
