# Code generated by weaver from telemetry/registry. DO NOT EDIT.
"""Attribute names and values of the kagent telemetry contract."""

from enum import StrEnum
from typing import Final

A2A_METHOD: Final = "a2a.method"
"""The A2A method that started the invocation."""

A2A_TASK_ID: Final = "a2a.task.id"
"""The A2A task that an invocation executes."""

A2A_TASK_STATE: Final = "a2a.task.state"
"""The A2A task state that execution reported."""

GEN_AI_AGENT_ID: Final = "gen_ai.agent.id"
"""The unique and stable identifier of the GenAI hosted agent resource."""

GEN_AI_AGENT_NAME: Final = "gen_ai.agent.name"
"""The human-readable name of the invoked GenAI agent."""

GEN_AI_CONVERSATION_ID: Final = "gen_ai.conversation.id"
"""The unique identifier for a conversation (session, thread), used to store and correlate messages within this conversation."""

GEN_AI_INPUT_MESSAGES: Final = "gen_ai.input.messages"
"""The chat history provided to the model as an input."""

GEN_AI_OPERATION_NAME: Final = "gen_ai.operation.name"
"""The name of the operation being performed."""

GEN_AI_OUTPUT_MESSAGES: Final = "gen_ai.output.messages"
"""Messages returned by the model where each message represents a specific model response (choice, candidate)."""

GEN_AI_PROVIDER_NAME: Final = "gen_ai.provider.name"
"""The Generative AI provider as identified by the client or server instrumentation."""

GEN_AI_REQUEST_MODEL: Final = "gen_ai.request.model"
"""The name of the GenAI model configured for the agent."""

KAGENT_CAPTURE_INPUT_TRUNCATED: Final = "kagent.capture.input_truncated"
"""Whether the captured input messages were shortened to the capture budget."""

KAGENT_CAPTURE_OUTPUT_TRUNCATED: Final = "kagent.capture.output_truncated"
"""Whether the captured output messages were shortened to the capture budget."""

KAGENT_GC_STAGE: Final = "kagent.gc.stage"
"""The stage of a runtime revision garbage collection attempt."""

KAGENT_INVOCATION_DISPOSITION: Final = "kagent.invocation.disposition"
"""How a segment stopped, when the task state does not say it."""

KAGENT_INVOCATION_RELATIONSHIP: Final = "kagent.invocation.relationship"
"""Why a segment links to another span."""

KAGENT_INVOCATION_SEGMENT: Final = "kagent.invocation.segment"
"""Whether an execution starts a task or continues it."""

KAGENT_RUNTIME: Final = "kagent.runtime"
"""The runtime that produces the model and tool spans of an agent."""


class A2aMethodValues(StrEnum):
    """Values of A2A_METHOD."""

    SEND_MESSAGE = "SendMessage"
    """A unary A2A request."""
    SEND_STREAMING_MESSAGE = "SendStreamingMessage"
    """A streaming A2A request."""


class A2aTaskStateValues(StrEnum):
    """Values of A2A_TASK_STATE."""

    SUBMITTED = "TASK_STATE_SUBMITTED"
    """The task was accepted."""
    WORKING = "TASK_STATE_WORKING"
    """The task is running."""
    COMPLETED = "TASK_STATE_COMPLETED"
    """The task finished."""
    FAILED = "TASK_STATE_FAILED"
    """The task failed."""
    CANCELED = "TASK_STATE_CANCELED"
    """The task was canceled."""
    INPUT_REQUIRED = "TASK_STATE_INPUT_REQUIRED"
    """The task waits for an approval or an answer."""
    REJECTED = "TASK_STATE_REJECTED"
    """The agent rejected the task."""
    AUTH_REQUIRED = "TASK_STATE_AUTH_REQUIRED"
    """The task waits for authentication."""


class GenAiOperationNameValues(StrEnum):
    """Values of GEN_AI_OPERATION_NAME."""

    CHAT = "chat"
    """Chat completion operation such as [OpenAI Chat API](https://platform.openai.com/docs/api-reference/chat)"""
    GENERATE_CONTENT = "generate_content"
    """Multimodal content generation operation such as [Gemini Generate Content](https://ai.google.dev/api/generate-content)"""
    TEXT_COMPLETION = "text_completion"
    """Text completions operation such as [OpenAI Completions API (Legacy)](https://platform.openai.com/docs/api-reference/completions)"""
    EMBEDDINGS = "embeddings"
    """Embeddings operation such as [OpenAI Create embeddings API](https://platform.openai.com/docs/api-reference/embeddings/create)"""
    RETRIEVAL = "retrieval"
    """Retrieval operation such as [OpenAI Search Vector Store API](https://platform.openai.com/docs/api-reference/vector-stores/search)"""
    FETCH_RESPONSE = "fetch_response"
    """Fetch a previously generated model response by its identifier, without performing inference, such as [OpenAI Get a model response](https://platform.openai.com/docs/api-reference/responses/get)"""
    CREATE_AGENT = "create_agent"
    """Create GenAI agent"""
    INVOKE_AGENT = "invoke_agent"
    """Invoke GenAI agent"""
    EXECUTE_TOOL = "execute_tool"
    """Execute a tool"""
    INVOKE_WORKFLOW = "invoke_workflow"
    """Invoke GenAI workflow"""
    PLAN = "plan"
    """Agent planning or task decomposition phase"""
    SEARCH_MEMORY = "search_memory"
    """Search/query memories from a memory store"""
    CREATE_MEMORY = "create_memory"
    """Create new memory records"""
    UPDATE_MEMORY = "update_memory"
    """Update existing memory records"""
    UPSERT_MEMORY = "upsert_memory"
    """Create or update memory records without the caller choosing which"""
    DELETE_MEMORY = "delete_memory"
    """Delete memory records"""
    CREATE_MEMORY_STORE = "create_memory_store"
    """Create or initialize a memory store"""
    DELETE_MEMORY_STORE = "delete_memory_store"
    """Delete or deprovision a memory store"""


class GenAiProviderNameValues(StrEnum):
    """Values of GEN_AI_PROVIDER_NAME."""

    OPENAI = "openai"
    """[OpenAI](https://openai.com/)"""
    GCP_GEN_AI = "gcp.gen_ai"
    """Any Google generative AI endpoint"""
    GCP_VERTEX_AI = "gcp.vertex_ai"
    """[Vertex AI](https://cloud.google.com/vertex-ai)"""
    GCP_GEMINI = "gcp.gemini"
    """[Gemini](https://cloud.google.com/products/gemini)"""
    ANTHROPIC = "anthropic"
    """[Anthropic](https://www.anthropic.com/)"""
    COHERE = "cohere"
    """[Cohere](https://cohere.com/)"""
    AZURE_AI_INFERENCE = "azure.ai.inference"
    """Azure AI Inference"""
    AZURE_AI_OPENAI = "azure.ai.openai"
    """[Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/overview)"""
    IBM_WATSONX_AI = "ibm.watsonx.ai"
    """[IBM Watsonx AI](https://www.ibm.com/products/watsonx-ai)"""
    AWS_BEDROCK = "aws.bedrock"
    """[AWS Bedrock](https://aws.amazon.com/bedrock)"""
    PERPLEXITY = "perplexity"
    """[Perplexity](https://www.perplexity.ai/)"""
    X_AI = "x_ai"
    """[xAI](https://x.ai/)"""
    DEEPSEEK = "deepseek"
    """[DeepSeek](https://www.deepseek.com/)"""
    GROQ = "groq"
    """[Groq](https://groq.com/)"""
    MISTRAL_AI = "mistral_ai"
    """[Mistral AI](https://mistral.ai/)"""
    MOONSHOT_AI = "moonshot_ai"
    """[Moonshot AI](https://www.moonshot.ai/)"""


class KagentGcStageValues(StrEnum):
    """Values of KAGENT_GC_STAGE."""

    DISCOVERY = "discovery"
    """Discovering cleanup-eligible persisted revisions."""
    COLLECTION = "collection"
    """Claiming, deleting compute for, or finalizing a revision."""


class KagentInvocationDispositionValues(StrEnum):
    """Values of KAGENT_INVOCATION_DISPOSITION."""

    CANCELED = "canceled"
    """A client asked to cancel the task."""
    ABANDONED = "abandoned"
    """The A2A event consumer stopped reading before execution finished."""
    INTERRUPTED = "interrupted"
    """The execution context ended without a cancellation request."""


class KagentInvocationRelationshipValues(StrEnum):
    """Values of KAGENT_INVOCATION_RELATIONSHIP."""

    RESUME_ORIGIN = "resume_origin"
    """The link from a resumed segment to the segment that started the native turn."""


class KagentInvocationSegmentValues(StrEnum):
    """Values of KAGENT_INVOCATION_SEGMENT."""

    INITIAL = "initial"
    """The first execution of a task."""
    RESUMED = "resumed"
    """An execution that continues a task after an approval or a question."""


class KagentRuntimeValues(StrEnum):
    """Values of KAGENT_RUNTIME."""

    ADK_GO = "adk-go"
    """The Go ADK runtime."""
    ADK_PYTHON = "adk-python"
    """The Python ADK runtime."""
    CLAUDE = "claude"
    """The Claude Code harness."""
    CODEX = "codex"
    """The Codex harness."""
    LANGGRAPH = "langgraph"
    """The LangGraph runtime."""
    CREWAI = "crewai"
    """The CrewAI runtime."""
    OPENAI_AGENTS = "openai-agents"
    """The OpenAI Agents SDK runtime."""
    BYO = "byo"
    """A bring-your-own image built on kagent-core."""
