apiVersion: kagent.dev/v1alpha3
kind: SandboxAgent
metadata:
  name: poem-flow-agent
  namespace: kagent
spec:
  description: A flow that uses a crew to generate a poem.
  type: BYO
  byo:
    image: localhost:5001/poem-flow:latest
    cmd: python
    args: [samples/crewai/poem_flow/src/poem_flow/main.py]
    env:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: kagent-openai
            key: OPENAI_API_KEY
