// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeApiV1alpha3 struct {
	*testing.Fake
}

func (c *FakeApiV1alpha3) AgentTemplates(namespace string) v1alpha3.AgentTemplateInterface {
	return newFakeAgentTemplates(c, namespace)
}

func (c *FakeApiV1alpha3) Harnesses(namespace string) v1alpha3.HarnessInterface {
	return newFakeHarnesses(c, namespace)
}

func (c *FakeApiV1alpha3) ModelConfigs(namespace string) v1alpha3.ModelConfigInterface {
	return newFakeModelConfigs(c, namespace)
}

func (c *FakeApiV1alpha3) RemoteMCPServers(namespace string) v1alpha3.RemoteMCPServerInterface {
	return newFakeRemoteMCPServers(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeApiV1alpha3) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
