// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgents implements AgentInterface
type fakeAgents struct {
	*gentype.FakeClientWithList[*v1alpha3.Agent, *v1alpha3.AgentList]
	Fake *FakeApiV1alpha3
}

func newFakeAgents(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.AgentInterface {
	return &fakeAgents{
		gentype.NewFakeClientWithList[*v1alpha3.Agent, *v1alpha3.AgentList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("agents"),
			v1alpha3.SchemeGroupVersion.WithKind("Agent"),
			func() *v1alpha3.Agent { return &v1alpha3.Agent{} },
			func() *v1alpha3.AgentList { return &v1alpha3.AgentList{} },
			func(dst, src *v1alpha3.AgentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.AgentList) []*v1alpha3.Agent { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha3.AgentList, items []*v1alpha3.Agent) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
