// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeRemoteMCPServers implements RemoteMCPServerInterface
type fakeRemoteMCPServers struct {
	*gentype.FakeClientWithList[*v1alpha3.RemoteMCPServer, *v1alpha3.RemoteMCPServerList]
	Fake *FakeApiV1alpha3
}

func newFakeRemoteMCPServers(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.RemoteMCPServerInterface {
	return &fakeRemoteMCPServers{
		gentype.NewFakeClientWithList[*v1alpha3.RemoteMCPServer, *v1alpha3.RemoteMCPServerList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("remotemcpservers"),
			v1alpha3.SchemeGroupVersion.WithKind("RemoteMCPServer"),
			func() *v1alpha3.RemoteMCPServer { return &v1alpha3.RemoteMCPServer{} },
			func() *v1alpha3.RemoteMCPServerList { return &v1alpha3.RemoteMCPServerList{} },
			func(dst, src *v1alpha3.RemoteMCPServerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.RemoteMCPServerList) []*v1alpha3.RemoteMCPServer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha3.RemoteMCPServerList, items []*v1alpha3.RemoteMCPServer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
