// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeSandboxTemplates implements SandboxTemplateInterface
type fakeSandboxTemplates struct {
	*gentype.FakeClientWithList[*v1alpha3.SandboxTemplate, *v1alpha3.SandboxTemplateList]
	Fake *FakeApiV1alpha3
}

func newFakeSandboxTemplates(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.SandboxTemplateInterface {
	return &fakeSandboxTemplates{
		gentype.NewFakeClientWithList[*v1alpha3.SandboxTemplate, *v1alpha3.SandboxTemplateList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("sandboxtemplates"),
			v1alpha3.SchemeGroupVersion.WithKind("SandboxTemplate"),
			func() *v1alpha3.SandboxTemplate { return &v1alpha3.SandboxTemplate{} },
			func() *v1alpha3.SandboxTemplateList { return &v1alpha3.SandboxTemplateList{} },
			func(dst, src *v1alpha3.SandboxTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.SandboxTemplateList) []*v1alpha3.SandboxTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha3.SandboxTemplateList, items []*v1alpha3.SandboxTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
