// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeHarnesses implements HarnessInterface
type fakeHarnesses struct {
	*gentype.FakeClientWithList[*v1alpha3.Harness, *v1alpha3.HarnessList]
	Fake *FakeApiV1alpha3
}

func newFakeHarnesses(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.HarnessInterface {
	return &fakeHarnesses{
		gentype.NewFakeClientWithList[*v1alpha3.Harness, *v1alpha3.HarnessList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("harnesses"),
			v1alpha3.SchemeGroupVersion.WithKind("Harness"),
			func() *v1alpha3.Harness { return &v1alpha3.Harness{} },
			func() *v1alpha3.HarnessList { return &v1alpha3.HarnessList{} },
			func(dst, src *v1alpha3.HarnessList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.HarnessList) []*v1alpha3.Harness { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha3.HarnessList, items []*v1alpha3.Harness) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
