// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentTemplates implements AgentTemplateInterface
type fakeAgentTemplates struct {
	*gentype.FakeClientWithList[*v1alpha3.AgentTemplate, *v1alpha3.AgentTemplateList]
	Fake *FakeApiV1alpha3
}

func newFakeAgentTemplates(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.AgentTemplateInterface {
	return &fakeAgentTemplates{
		gentype.NewFakeClientWithList[*v1alpha3.AgentTemplate, *v1alpha3.AgentTemplateList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("agenttemplates"),
			v1alpha3.SchemeGroupVersion.WithKind("AgentTemplate"),
			func() *v1alpha3.AgentTemplate { return &v1alpha3.AgentTemplate{} },
			func() *v1alpha3.AgentTemplateList { return &v1alpha3.AgentTemplateList{} },
			func(dst, src *v1alpha3.AgentTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.AgentTemplateList) []*v1alpha3.AgentTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha3.AgentTemplateList, items []*v1alpha3.AgentTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
