// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeModelConfigs implements ModelConfigInterface
type fakeModelConfigs struct {
	*gentype.FakeClientWithList[*v1alpha3.ModelConfig, *v1alpha3.ModelConfigList]
	Fake *FakeApiV1alpha3
}

func newFakeModelConfigs(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.ModelConfigInterface {
	return &fakeModelConfigs{
		gentype.NewFakeClientWithList[*v1alpha3.ModelConfig, *v1alpha3.ModelConfigList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("modelconfigs"),
			v1alpha3.SchemeGroupVersion.WithKind("ModelConfig"),
			func() *v1alpha3.ModelConfig { return &v1alpha3.ModelConfig{} },
			func() *v1alpha3.ModelConfigList { return &v1alpha3.ModelConfigList{} },
			func(dst, src *v1alpha3.ModelConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.ModelConfigList) []*v1alpha3.ModelConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha3.ModelConfigList, items []*v1alpha3.ModelConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
