apiVersion: kagent.dev/v1alpha3
kind: SandboxAgent
metadata:
  name: basic-agent
spec:
  description: This agent can do anything.
  type: BYO
  byo:
    image: localhost:5001/my-byo:latest
    cmd: basic
    env:
      - name: GOOGLE_API_KEY
        valueFrom:
          secretKeyRef:
            name: kagent-google
            key: GOOGLE_API_KEY
