// Code generated by weaver from telemetry/registry. DO NOT EDIT.

// Package conv holds the attribute and metric names of the kagent telemetry contract.
package conv

import "go.opentelemetry.io/otel/attribute"

const (
	// A2AMethodKey is "a2a.method". The A2A method that started the invocation.
	A2AMethodKey = attribute.Key("a2a.method")
	// A2ATaskIDKey is "a2a.task.id". The A2A task that an invocation executes.
	A2ATaskIDKey = attribute.Key("a2a.task.id")
	// A2ATaskStateKey is "a2a.task.state". The A2A task state that execution reported.
	A2ATaskStateKey = attribute.Key("a2a.task.state")
	// GenAIAgentIDKey is "gen_ai.agent.id". The unique and stable identifier of the GenAI hosted agent resource.
	GenAIAgentIDKey = attribute.Key("gen_ai.agent.id")
	// GenAIAgentNameKey is "gen_ai.agent.name". The human-readable name of the invoked GenAI agent.
	GenAIAgentNameKey = attribute.Key("gen_ai.agent.name")
	// GenAIConversationIDKey is "gen_ai.conversation.id". The unique identifier for a conversation (session, thread), used to store and correlate messages within this conversation.
	GenAIConversationIDKey = attribute.Key("gen_ai.conversation.id")
	// GenAIInputMessagesKey is "gen_ai.input.messages". The chat history provided to the model as an input.
	GenAIInputMessagesKey = attribute.Key("gen_ai.input.messages")
	// GenAIOperationNameKey is "gen_ai.operation.name". The name of the operation being performed.
	GenAIOperationNameKey = attribute.Key("gen_ai.operation.name")
	// GenAIOutputMessagesKey is "gen_ai.output.messages". Messages returned by the model where each message represents a specific model response (choice, candidate).
	GenAIOutputMessagesKey = attribute.Key("gen_ai.output.messages")
	// GenAIProviderNameKey is "gen_ai.provider.name". The Generative AI provider as identified by the client or server instrumentation.
	GenAIProviderNameKey = attribute.Key("gen_ai.provider.name")
	// GenAIRequestModelKey is "gen_ai.request.model". The name of the GenAI model configured for the agent.
	GenAIRequestModelKey = attribute.Key("gen_ai.request.model")
	// KagentCaptureInputTruncatedKey is "kagent.capture.input_truncated". Whether the captured input messages were shortened to the capture budget.
	KagentCaptureInputTruncatedKey = attribute.Key("kagent.capture.input_truncated")
	// KagentCaptureOutputTruncatedKey is "kagent.capture.output_truncated". Whether the captured output messages were shortened to the capture budget.
	KagentCaptureOutputTruncatedKey = attribute.Key("kagent.capture.output_truncated")
	// KagentGCStageKey is "kagent.gc.stage". The stage of a runtime revision garbage collection attempt.
	KagentGCStageKey = attribute.Key("kagent.gc.stage")
	// KagentInvocationDispositionKey is "kagent.invocation.disposition". How a segment stopped, when the task state does not say it.
	KagentInvocationDispositionKey = attribute.Key("kagent.invocation.disposition")
	// KagentInvocationRelationshipKey is "kagent.invocation.relationship". Why a segment links to another span.
	KagentInvocationRelationshipKey = attribute.Key("kagent.invocation.relationship")
	// KagentInvocationSegmentKey is "kagent.invocation.segment". Whether an execution starts a task or continues it.
	KagentInvocationSegmentKey = attribute.Key("kagent.invocation.segment")
	// KagentRuntimeKey is "kagent.runtime". The runtime that produces the model and tool spans of an agent.
	KagentRuntimeKey = attribute.Key("kagent.runtime")
)

// Values of A2AMethodKey.
const (
	// A2AMethodSendMessage: A unary A2A request.
	A2AMethodSendMessage = "SendMessage"
	// A2AMethodSendStreamingMessage: A streaming A2A request.
	A2AMethodSendStreamingMessage = "SendStreamingMessage"
)

// Values of A2ATaskStateKey.
const (
	// A2ATaskStateSubmitted: The task was accepted.
	A2ATaskStateSubmitted = "TASK_STATE_SUBMITTED"
	// A2ATaskStateWorking: The task is running.
	A2ATaskStateWorking = "TASK_STATE_WORKING"
	// A2ATaskStateCompleted: The task finished.
	A2ATaskStateCompleted = "TASK_STATE_COMPLETED"
	// A2ATaskStateFailed: The task failed.
	A2ATaskStateFailed = "TASK_STATE_FAILED"
	// A2ATaskStateCanceled: The task was canceled.
	A2ATaskStateCanceled = "TASK_STATE_CANCELED"
	// A2ATaskStateInputRequired: The task waits for an approval or an answer.
	A2ATaskStateInputRequired = "TASK_STATE_INPUT_REQUIRED"
	// A2ATaskStateRejected: The agent rejected the task.
	A2ATaskStateRejected = "TASK_STATE_REJECTED"
	// A2ATaskStateAuthRequired: The task waits for authentication.
	A2ATaskStateAuthRequired = "TASK_STATE_AUTH_REQUIRED"
)

// Values of GenAIOperationNameKey.
const (
	// GenAIOperationNameChat: Chat completion operation such as [OpenAI Chat API](https://platform.openai.com/docs/api-reference/chat)
	GenAIOperationNameChat = "chat"
	// GenAIOperationNameGenerateContent: Multimodal content generation operation such as [Gemini Generate Content](https://ai.google.dev/api/generate-content)
	GenAIOperationNameGenerateContent = "generate_content"
	// GenAIOperationNameTextCompletion: Text completions operation such as [OpenAI Completions API (Legacy)](https://platform.openai.com/docs/api-reference/completions)
	GenAIOperationNameTextCompletion = "text_completion"
	// GenAIOperationNameEmbeddings: Embeddings operation such as [OpenAI Create embeddings API](https://platform.openai.com/docs/api-reference/embeddings/create)
	GenAIOperationNameEmbeddings = "embeddings"
	// GenAIOperationNameRetrieval: Retrieval operation such as [OpenAI Search Vector Store API](https://platform.openai.com/docs/api-reference/vector-stores/search)
	GenAIOperationNameRetrieval = "retrieval"
	// GenAIOperationNameFetchResponse: Fetch a previously generated model response by its identifier, without performing inference, such as [OpenAI Get a model response](https://platform.openai.com/docs/api-reference/responses/get)
	GenAIOperationNameFetchResponse = "fetch_response"
	// GenAIOperationNameCreateAgent: Create GenAI agent
	GenAIOperationNameCreateAgent = "create_agent"
	// GenAIOperationNameInvokeAgent: Invoke GenAI agent
	GenAIOperationNameInvokeAgent = "invoke_agent"
	// GenAIOperationNameExecuteTool: Execute a tool
	GenAIOperationNameExecuteTool = "execute_tool"
	// GenAIOperationNameInvokeWorkflow: Invoke GenAI workflow
	GenAIOperationNameInvokeWorkflow = "invoke_workflow"
	// GenAIOperationNamePlan: Agent planning or task decomposition phase
	GenAIOperationNamePlan = "plan"
	// GenAIOperationNameSearchMemory: Search/query memories from a memory store
	GenAIOperationNameSearchMemory = "search_memory"
	// GenAIOperationNameCreateMemory: Create new memory records
	GenAIOperationNameCreateMemory = "create_memory"
	// GenAIOperationNameUpdateMemory: Update existing memory records
	GenAIOperationNameUpdateMemory = "update_memory"
	// GenAIOperationNameUpsertMemory: Create or update memory records without the caller choosing which
	GenAIOperationNameUpsertMemory = "upsert_memory"
	// GenAIOperationNameDeleteMemory: Delete memory records
	GenAIOperationNameDeleteMemory = "delete_memory"
	// GenAIOperationNameCreateMemoryStore: Create or initialize a memory store
	GenAIOperationNameCreateMemoryStore = "create_memory_store"
	// GenAIOperationNameDeleteMemoryStore: Delete or deprovision a memory store
	GenAIOperationNameDeleteMemoryStore = "delete_memory_store"
)

// Values of GenAIProviderNameKey.
const (
	// GenAIProviderNameOpenAI: [OpenAI](https://openai.com/)
	GenAIProviderNameOpenAI = "openai"
	// GenAIProviderNameGCPGenAI: Any Google generative AI endpoint
	GenAIProviderNameGCPGenAI = "gcp.gen_ai"
	// GenAIProviderNameGCPVertexAI: [Vertex AI](https://cloud.google.com/vertex-ai)
	GenAIProviderNameGCPVertexAI = "gcp.vertex_ai"
	// GenAIProviderNameGCPGemini: [Gemini](https://cloud.google.com/products/gemini)
	GenAIProviderNameGCPGemini = "gcp.gemini"
	// GenAIProviderNameAnthropic: [Anthropic](https://www.anthropic.com/)
	GenAIProviderNameAnthropic = "anthropic"
	// GenAIProviderNameCohere: [Cohere](https://cohere.com/)
	GenAIProviderNameCohere = "cohere"
	// GenAIProviderNameAzureAIInference: Azure AI Inference
	GenAIProviderNameAzureAIInference = "azure.ai.inference"
	// GenAIProviderNameAzureAIOpenAI: [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/overview)
	GenAIProviderNameAzureAIOpenAI = "azure.ai.openai"
	// GenAIProviderNameIBMWatsonxAI: [IBM Watsonx AI](https://www.ibm.com/products/watsonx-ai)
	GenAIProviderNameIBMWatsonxAI = "ibm.watsonx.ai"
	// GenAIProviderNameAWSBedrock: [AWS Bedrock](https://aws.amazon.com/bedrock)
	GenAIProviderNameAWSBedrock = "aws.bedrock"
	// GenAIProviderNamePerplexity: [Perplexity](https://www.perplexity.ai/)
	GenAIProviderNamePerplexity = "perplexity"
	// GenAIProviderNameXAI: [xAI](https://x.ai/)
	GenAIProviderNameXAI = "x_ai"
	// GenAIProviderNameDeepseek: [DeepSeek](https://www.deepseek.com/)
	GenAIProviderNameDeepseek = "deepseek"
	// GenAIProviderNameGroq: [Groq](https://groq.com/)
	GenAIProviderNameGroq = "groq"
	// GenAIProviderNameMistralAI: [Mistral AI](https://mistral.ai/)
	GenAIProviderNameMistralAI = "mistral_ai"
	// GenAIProviderNameMoonshotAI: [Moonshot AI](https://www.moonshot.ai/)
	GenAIProviderNameMoonshotAI = "moonshot_ai"
)

// Values of KagentGCStageKey.
const (
	// KagentGCStageDiscovery: Discovering cleanup-eligible persisted revisions.
	KagentGCStageDiscovery = "discovery"
	// KagentGCStageCollection: Claiming, deleting compute for, or finalizing a revision.
	KagentGCStageCollection = "collection"
)

// Values of KagentInvocationDispositionKey.
const (
	// KagentInvocationDispositionCanceled: A client asked to cancel the task.
	KagentInvocationDispositionCanceled = "canceled"
	// KagentInvocationDispositionAbandoned: The A2A event consumer stopped reading before execution finished.
	KagentInvocationDispositionAbandoned = "abandoned"
	// KagentInvocationDispositionInterrupted: The execution context ended without a cancellation request.
	KagentInvocationDispositionInterrupted = "interrupted"
)

// Values of KagentInvocationRelationshipKey.
const (
	// KagentInvocationRelationshipResumeOrigin: The link from a resumed segment to the segment that started the native turn.
	KagentInvocationRelationshipResumeOrigin = "resume_origin"
)

// Values of KagentInvocationSegmentKey.
const (
	// KagentInvocationSegmentInitial: The first execution of a task.
	KagentInvocationSegmentInitial = "initial"
	// KagentInvocationSegmentResumed: An execution that continues a task after an approval or a question.
	KagentInvocationSegmentResumed = "resumed"
)

// Values of KagentRuntimeKey.
const (
	// KagentRuntimeADKGo: The Go ADK runtime.
	KagentRuntimeADKGo = "adk-go"
	// KagentRuntimeADKPython: The Python ADK runtime.
	KagentRuntimeADKPython = "adk-python"
	// KagentRuntimeClaude: The Claude Code harness.
	KagentRuntimeClaude = "claude"
	// KagentRuntimeCodex: The Codex harness.
	KagentRuntimeCodex = "codex"
	// KagentRuntimeLangGraph: The LangGraph runtime.
	KagentRuntimeLangGraph = "langgraph"
	// KagentRuntimeCrewAI: The CrewAI runtime.
	KagentRuntimeCrewAI = "crewai"
	// KagentRuntimeOpenAIAgents: The OpenAI Agents SDK runtime.
	KagentRuntimeOpenAIAgents = "openai-agents"
	// KagentRuntimeBYO: A bring-your-own image built on kagent-core.
	KagentRuntimeBYO = "byo"
)

// KagentRuntimeRevisionGCDuration: Duration of a runtime revision garbage collection attempt.
const (
	KagentRuntimeRevisionGCDuration            = "kagent.runtime_revision.gc.duration"
	KagentRuntimeRevisionGCDurationUnit        = "s"
	KagentRuntimeRevisionGCDurationDescription = "Duration of a runtime revision garbage collection attempt."
)

// KagentRuntimeRevisionGCPending: Number of cleanup-eligible runtime revisions in the last successful discovery.
const (
	KagentRuntimeRevisionGCPending            = "kagent.runtime_revision.gc.pending"
	KagentRuntimeRevisionGCPendingUnit        = "{revision}"
	KagentRuntimeRevisionGCPendingDescription = "Number of cleanup-eligible runtime revisions in the last successful discovery."
)
